### ISSUE TITLE
Import statements in Examples are wrong

### ISSUE THREAD

**Issue by FruitVul** [luckystarufo/pySINDy#15]
When I tried to run the SINDy: Van Der Pol Oscillator example on my local machine the imports didn't work.
For example `from pySINDy.sindy import SINDy` should be `from pysindy import SINDy`
Besides that I couldnt figure out how `from pySINDy.utils.generator import van_der_pol_generator`

Installed PySINDy with pip install...

**Comment by FruitVul** [comment]
Seems like the Issue lies within the installation with pip. Installing from source solved my issues.

**Comment by luckystarufo** [comment]
Hey Philipp, thanks for the feedbacks!
And actually this repo is experiencing an upgrade recently ... You can see the latest (official) version here: https://github.com/dynamicslab/pysindy
