### ISSUE TITLE
pip install doesn't seem to work

### ISSUE THREAD

**Issue by dacb** [luckystarufo/pySINDy#2]
```
[dacb@localhost ~/tmp]$ pip install pysindy
Collecting pysindy
  Could not find a version that satisfies the requirement pysindy (from versions: )
No matching distribution found for pysindy
```

**Comment by luckystarufo** [comment]
Yes, you are correct. 
We haven't uploaded the distribution to PyPI yet but we will do by the end of the week.
Right now the repo is just for the demo purpose.

**Comment by dacb** [comment]
I would say don’t bother to respond, just fix and close.

--
David A. C. Beck, Ph.D.
dacb@uw.edu
http://faculty.washington.edu/dacb/
Research Associate Professor, Dept. of Chemical Engineering
Director of Research & Senior Data Science Fellow - eScience Institute
Adjunct Associate Professor of Paul G. Allen School of Computer Science & Engineering 
Adjunct Research Associate Professor, Env. and Occ. Health Sciences
Associate Director - NRT Data Intensive Research Enabling Clean Technologies
University of Washington, Seattle

**Comment by dacb** [comment]
Hurray!  It works.
