### ISSUE TITLE
Problem with data file for example 3 notebook

### ISSUE THREAD

**Issue by amarandon** [luckystarufo/pySINDy#7]
I tried to run `examples/example-3-sindypde-reactiondiffusion.ipynb` but I get this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/reaction_diffusion.mat'
```

I noticed that there's a similar file with a `.m` extension so I renamed it to `.mat` but then I get a different error:
```
ValueError: Unknown mat file type, version 95, 116
```

**Comment by luckystarufo** [comment]
yes, that's because reaction_diffusion.mat is too large to upload on Github, so we delete it.
However, you can use Matlab to run reaction_diffusion.m which generates reaction_diffusion.mat
